[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "crealand"
version = "1.0.9"
description = "Python SDK for the Crealand API"
authors = [
    { name = "UBTECH Robotics", email = "swenggroup@ubtrobot.com" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [

]
license = {file = "LICENSE"}
keywords = ["Crealand", "UBTECH Robotics Crealand"]