[tool.poetry]
name = "asmbly-neon-integrations"
version = "0.1.10"
description = "Various convenience functions and scripts for managing integrations at Asmbly Makerspace."
authors = ["Matthew Miller <matthew.miller@asmbly.org>"]
license = "GPL-3.0-or-later"
readme = "README.md"
packages = [
    { include = "asmbly_neon_integrations" }
]

[tool.poetry.dependencies]
python = ">=3.9"
aiohttp = "^3.9.5"
requests = "^2.32.3"
pytz = "^2024.1"
boto3 = "^1.35.47"
pydantic = "^2.9.2"
mailjet-rest = "^1.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
