# pyproject.toml
# Python project metadata and build settings for this code base.
# Documentation:
#     <URL:https://peps.python.org/pep-0517/>
#     <URL:https://peps.python.org/pep-0518/>
#     <URL:https://peps.python.org/pep-0621/>

[project]

# Name of the Python distribution to build.
name = "changelog-chug"

# Text file containing detailed description of the distribution.
readme = { file = "README", content-type = "text/x-rst" }

# Keywords to categorise this project.
keywords = ["version", "changelog", "release", "packaging"]

# Trove classifiers for this project.
# Reference: <URL:https://pypi.org/classifiers/>
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    ]

# The Python version requirements of the project.
requires-python = ">= 3.7"

# Core dependencies required for the package to operate.
dependencies = [

    # Semantic Versioning implementation.
    # Documentation: <URL:https://python-semver.readthedocs.io/>.
    "semver >= 3.0.0",

    # Python Documentation Utilities.
    # Documentation: <URL:https://docutils.sourceforge.io/docs/>.
    "docutils >= 0.21.0",

    ]

# The license granted to recipients of this project.
license = { file = "COPYING" }

# The persons or entities considered the authors of this project.
authors = [
    { name = "Ben Finney", email = "ben+python@benfinney.id.au" },
    ]

# Names of fields that must be dynamically computed by the build system.
dynamic = [
    "description",
    "version",
    "maintainers",
    ]

[project.optional-dependencies]

static-analysis = [

    # Pip version inspector that reports PyPI available updates.
    # Homepage: <URL:https://github.com/bartTC/pip-check/>.
    "pip-check",

    # McCabe code complexity measurement tool.
    # Documentation: <URL:https://github.com/pycqa/mccabe>.
    "mccabe ~= 0.7",

    # Static code checker for Python style recommendations.
    # Documentation: <URL:https://pycodestyle.pycqa.org/>.
    "pycodestyle ~= 2.12",

    # Python linter and code formatter.
    # Documentation: <URL:https://docs.astral.sh/ruff/>.
    "ruff ~= 0.6",

    ]

test = [

    "changelog-chug[static-analysis]",

    # Extensions to the Python ‘unittest’ framework.
    # Documentation: <URL:https://testtools.readthedocs.org/>.
    "testtools",

    # Data-driven test scenarios for ‘unittest’.
    # Documentation: <URL:https://pypi.org/project/testscenarios/>.
    "testscenarios >= 0.4",

    # Code coverage measurement.
    # Documentation: <URL:https://coverage.readthedocs.io/>.
    "coverage",

    ]

devel = [

    "changelog-chug[test]",

    # Tool to upgrade Python syntax for newer versions.
    # Documentation: <URL:https://github.com/asottile/pyupgrade>.
    "pyupgrade ~= 3.17",

    # Python ‘import’ statement sorter.
    # Documentation: <URL:https://pycqa.github.io/isort/>.
    "isort ~= 5.13",

    ]

build = [

    "changelog-chug[devel]",

    # Reference implementation of Python wheel packaging standard (PEP 427).
    # Documentation: <URL:https://wheel.readthedocs.io/>.
    "wheel",

    # A simple, correct (defined by PEP 517) Python build frontend.
    # Documentation: <URL:https://build.pypa.io/>.
    "build",

    ]

publish = [

    "changelog-chug[build]",

    # Collection of utilities for publishing packages on PyPI.
    # Documentation: <URL:https://twine.readthedocs.io/>.
    "twine",

    ]

[project.urls]
"Home Page" = "https://git.sr.ht/~bignose/changelog-chug"
"Change Log" = """
    https://git.sr.ht/~bignose/changelog-chug/tree/main/item/ChangeLog
    """
"Source" = "https://git.sr.ht/~bignose/changelog-chug"
"Issue Tracker" = "https://todo.sr.ht/~bignose/changelog-chug"

[build-system]

# Minimum requirements for the build system.
requires = [

    # Framework for working with Python packages.
    # Documentation: <URL:https://setuptools.pypa.io/>.
    "setuptools >= 62.4.0",

    # Semantic Versioning implementation.
    # Documentation: <URL:https://python-semver.readthedocs.io/>.
    "semver >= 3.0.0",

    # Python Documentation Utilities.
    # Documentation: <URL:https://docutils.sourceforge.io/docs/>.
    "docutils >= 0.21.0",

    ]

# Path to the Python object to perform the build.
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]

# Folders that contain the packages (default: ["."])
where = ["src"]


[tool.coverage.run]

# Source (packages or directories) to measure during execution.
source = [
    "src",
    "util",
    ]


# Local-variables:
# coding: utf-8
# mode: conf
# mode: toml
# End:
# vim: fileencoding=utf-8 filetype=toml :
