[build-system]
requires = [
    "hatchling>=1.22.2"
]
build-backend = "hatchling.build"

[project]
name = "pypomes_core"
version = "1.5.9"
authors = [
  { name="GT Nunes", email="wisecoder01@gmail.com" }
]
description = "A collection of Python pomes, penyeach (core modules)"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "filetype>=1.2.0",
    "Flask>=3.0.3",
    "pip>=24.2",
    "python-dateutil>=2.9.0",
    "pytz>=2024.2",
    "requests>=2.32.3",
    "setuptools>=75.2.0",
    "Werkzeug>=3.0.4",
    "wheel>=0.44.0",
    "xmltodict3>=0.0.4"
]

[project.urls]
"Homepage" = "https://github.com/TheWiseCoder/PyPomes-Core"
"Bug Tracker" = "https://github.com/TheWiseCoder/PyPomes-Core/issues"
