[tool.poetry]
name = "fr_common_lib"
version = "0.4.1"
description = "Библиотека переиспользуемых компонентов"
authors = ["lagunovartur <lagunovartur@inbox.ru>"]
license = "MIT"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"