[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ckanext-latex"
description = "LaTeX syntax support for form and display"
version = "1.0.0"
keywords = []

authors = [
    {name = "DataShades", email = "datashades@linkdigital.com.au"},
    {name = "Oleksandr Cherniavskyi", email = "mutantsan@gmail.com"},
]
maintainers = [
    {name = "DataShades", email = "datashades@linkdigital.com.au"},
]

readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
test = ["pytest-ckan", "ckanext-toolbelt", "requests-mock"]
dev = ["pytest-ckan", "ckanext-toolbelt", "requests-mock"]

[project.urls]
Homepage = "https://github.com/DataShades/ckanext-latex"

[project.entry-points."ckan.plugins"]
charts_view = "ckanext.latex.plugin:LatexPlugin"
