[build-system]
requires = ["setuptools>=60.0"]
build-backend = "setuptools.build_meta"
[project]
name = "psplpy"
version = "1.18.2"
authors = []
description = "The Personal Study Purposes Library of PYthon."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pika",
    "pyyaml",
    "requests",
    "opencv-python",
    "opencv-python-headless",
    "pillow<=9.5.0",
    "pyautogui",
    "pynput",
    "numpy<=1.26.4"
]
