[tool.poetry]
name = "fastapi-observability"
version = "0.0.1.dev20922"
description = "A middleware and instrumentation library for FastAPI to enable Prometheus metrics and OpenTelemetry tracing."
authors = ["Pavel <mulin.pasha@gmail.com>"]
readme = "README.md"
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = ">0.112.2"
opentelemetry-api = "^1.27.0"
opentelemetry-sdk = "^1.27.0"
opentelemetry-instrumentation-fastapi = "^0.48b0"
opentelemetry-exporter-otlp = "^1.27.0"
opentelemetry-instrumentation-logging = "^0.48b0"
prometheus-client = "^0.21.0"
starlette = ">=0.41.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
