[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["subscription"]

[project]
name = "django-enhanced-subscriptions"
version = "1.0.0"
description = "This Django library provides a comprehensive solution for managing subscriptions, feature access and wallet functionality"
readme = "README.rst"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Josephat Macharia", email = "josemash4@gmail.com"},
]
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 5.0",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Internet :: WWW/HTTP",
]
dependencies = [
    "Django>=5.0.6",
]

[project.urls]
Homepage = "https://github.com/joemash/django_enhanced_subscriptions"

[project.optional-dependencies]
test = [
    "pytest>=8.2.1",
    "pytest-django>=4.8.0",
    "model-bakery>=1.18.1",
    "flake8",
    "isort",
    "black",
    "tox",
    "coverage",
    "pytest-cov",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"
python_files = ["test_*.py"]
addopts = "-v"
django_find_project = false
pythonpath = [
    ".",
    "tests"
]

[tool.flake8]
max-line-length = 99