[build-system]
requires = ['setuptools>=42', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'online-store-pdp'
version = '0.1.0'
description = 'Исполняемый пакет для управления пользователями и заказами в онлайн-магазине'
authors = [
  {name = 'Whisse', email = 'lord18201@yandex.ru'}
]
readme = 'README.md'
license = {text = 'MIT'}
requires-python = '>=3.8'
dependencies = [
]