[tool.poetry]
name = "nonebot-plugin-searchgames"
version = "0.1.4"
description = "简单查询游戏steam和switch平台游戏信息的小插件"
authors = ["NYAGO666"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/NYAGO666/nonebot-plugin-Searchgames"
repository = "https://github.com/NYAGO666/nonebot-plugin-Searchgames"
packages = [  
    { include = "nonebot_plugin_searchgames" }  
]

[tool.poetry.dependencies]
python = ">3.10"
httpx = ">=0.27.0"
nonebot2 = ">=2.3.0"
pydantic = ">=2.8.0"
nonebot-adapter-onebot = ">=2.4.0"
nonebot-plugin-htmlrender = ">=0.3.0"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
