[tool.poetry]
name = "pydantic-gql"
# Version is overwritten at build time by CI based on git tag
version = "1.2.0"
description = "A simple GraphQL query builder based on Pydantic models"
authors = ["Abraham Murciano <abrahammurciano@gmail.com>"]
license = "GPLv3"
readme = "README.md"
repository = "https://github.com/abrahammurciano/pydantic-gql"
documentation = "https://abrahammurciano.github.io/pydantic-gql/pydantic-gql"
keywords = []

[tool.poetry.dependencies]
python = ">=3.12"
pydantic = "^2.9.2"

[tool.poetry.group.dev.dependencies]
pytest = "*"
black = "*"
pdoc3 = "*"
toml = "*"
types-toml = "*"
mypy = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
exclude = [".venv", "venv"]
