[project]
name = "package-schemes"
version = "0.1.0"
description = "Schemas and interfaces describing python packages"
readme = "readme.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.0.0",
    "toml>=0.10.0",
]

[tool.uv]
package = true
dev-dependencies = [
    "mypy>=1.12.1",
    "pre-commit>=4.0.1",
    "pre-commit-hooks>=5.0.0",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.24.0",
    "pytest-cov>=5.0.0",
    "ruff>=0.7.0",
    "types-toml>=0.10.8.20240310",
    "httpx>=0.27.2",
    "pytest-xdist>=3.6.1",
]

[tool.black]
skip-string-normalization = true
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.ruff]
line-length = 120
target-version = "py39"
unsafe-fixes = true

[tool.ruff.format]
preview = true
quote-style = "single"

[tool.ruff.lint]
preview = true
select = ["A", "B", "C", "D", "E", "F", "I"]
fixable = ["A", "B", "C", "D", "E", "F", "I"]
ignore = ["UP004", "D100", "D101", "D102", "D103", "D104", "D107", "D415", "D105", "D106", "D203", "D213", "B008"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.coverage.run]
omit = [
    "*/tests/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
]

[tool.pytest.ini_options]
addopts = "-vvs --tb=short -n 4"
testpaths = [
    "tests",
    "integration",
]
python_files = [
    "tests/*.py",
    "test_*.py"
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore:Module already imported:pytest.PytestWarning"
]
log_cli=true
log_level='INFO'
xfail_strict = true
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
