[project]
name = "py-awesome-scripts"
version = "0.2.3"
description = "Awesome python script tools."
readme = "README.md"
requires-python = ">=3.8,<3.9"
dependencies = [
    "docx2pdf>=0.1.8",
    "numpy>=1.24.4",
    "pycdlib>=1.14.0",
    "pyfiglet>=0.8.post1",
    "pygame>=2.6.1",
    "pypdf>=5.0.1",
    "pyside2>=5.15.2.1",
    "requests>=2.32.3",
    "rtoml>=0.11.0",
    "torch>=2.4.1",
    "torchaudio>=2.4.1",
    "torchvision>=0.19.1",
]
[tool.uv]
index-url = 'https://pypi.tuna.tsinghua.edu.cn/simple/'
dev-dependencies = [
    "maturin>=1.7.4",
    "mypy>=1.12.0",
    "pip>=24.2",
    "ruff>=0.7.0",
    "setuptools>=75.2.0",
]
[tool.ruff]
line-length = 80 # 代码最大行宽
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
