[tool.poetry]
authors = ["Sasha Koss <koss@nocorp.me>"]
description = "Mind Control types"
license = "UNLICENSED"
name = "mindcontrol-types"
readme = "README.md"
version = "0.4.0"

packages = [{ include = "mindcontrol_types" }]

[tool.poetry.dependencies]
python = "^3.8"
typing-extensions = "^4"
pydantic = "^2.9"
genotype-runtime = "^0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
