[tool.poetry]
name = "textual-pyfiglet"
version = "0.4.0"
description = "A Widget implementation of PyFiglet for Textual"
authors = ["edward-jazzhands <ed.jazzhands@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/edward-jazzhands/textual-pyfiglet"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
textual = ">=0.74.0"
textual-pyfiglet-fonts = { version = ">=0.2.0", optional = true }

[tool.poetry.extras]
fonts = ["textual-pyfiglet-fonts"]

[tool.poetry.group.dev.dependencies]
textual-dev = "^1.3.0"
pytest = ">=7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# This is for running the demo
[tool.poetry.scripts]
textual-pyfiglet = "textual_pyfiglet.__main__:main"
