[tool.poetry]
name = "quipus"
version = "0.1.1"
description = ""
authors = [
    "Jorge U. Alarc√≥n <j1dev@proton.me>",
    "Fernando Nicolas Carrillo Lopez <pandasoncode@gmail.com>",
]
readme = "README.md"
package-mode = true
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.12"
weasyprint = "62.3"
paramiko = "3.4.1,<3.5.0"
boto3 = "^1.35.34"
pandas = "^2.2.3"
psycopg = "^3.2.3"
psycopg-pool = "^3.2.3"

[tool.poetry.group.dev.dependencies]
pylint = "^3.3.1"
black = "^24.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
