[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sub-byte"
version = "0.0.1"
authors = [{name = "James Parrott", email = "james.parrott@proton.me"}]
description = "Encodes and decodes sequences of integers with known widths, and sequences of symbols equivalent to integers under some mapping. "
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.9"
keywords = ["Encoders", "Serialization"]
license = {file = "LICENSE.md"}
classifiers = [
    "Programming Language :: Python",
]
dependencies = [
    "more_itertools",
]
[project.optional-dependencies]
test = [
    "pytest",
    "hypothesis",
]






