[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tuze_package_sample"
version = "1.0.0"
description = "A useful tool package"
readme = "README.md"
requires-python = ">=3.6"
license = {text = "MIT"}
authors = [
    { name = "tuze", email = "sharkshore@163.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
    "colorama",
]

[project.urls]
"Homepage" = "https://github.com/sharkshore/python-base-sample"

