[tool.poetry]
name = "instagram-auth"
version = "0.1.5"
description = "Instagram Web Auth"
authors = ["Николай Витальевич Никоноров <nnv@bitt.moe>"]
readme = "README.md"
packages = [{include = "instagram_auth"}]
repository = "https://gitlab.com/bitt_moe/instagram/auth.git"

[tool.poetry.dependencies]
python = "^3.10"
cffi = "1.16.0"
pycparser = "2.21"
pycryptodomex = "3.19.1"
PyNaCl = "1.5.0"
aiohappyeyeballs = "2.4.3"
aiohttp = "3.10.9"
aiosignal = "1.3.1"
async-timeout = "4.0.3"
attrs = "24.2.0"
frozenlist = "1.4.1"
idna = "3.10"
multidict = "6.1.0"
typing_extensions = "4.12.2"
yarl = "1.13.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
