[tool.poetry]
name = "mic-toolkit"
version = "0.2.2"
description = "Internal toolkit for Microsoft Innovations Club VITC."
authors = ["Ameen Shaikh <mohammedameen9011@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
llama-index = "^0.11.9"
llama-index-llms-vllm = "^0.2.0"
llama-index-llms-openai-like = "^0.2.0"
openai = "^1.45.1"
langchain = "^0.3.0"
langchain-community = "^0.3.0"
datasets = "^3.0.0"
distilabel = {extras = ["openai"], version = "^1.4.1"}


[tool.poetry.group.dev.dependencies]
mkdocstrings = {extras = ["python"], version = "^0.26.1"}
mkdocs-material = "^9.5.34"
mkdocs = "^1.6.1"
pre-commit = "^3.8.0"
ipykernel = "^6.29.5"
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  "."
]