[project]
name = "uv-audit"
version = "0.1.1"
description = "uv Tool for checking dependencies for vulnerabilities"
readme = "readme.md"
requires-python = ">=3.12"
dependencies = [
    "typer>=0.12.5",
    "toml>=0.10.2",
    "pyproject-api>=1.5.0",
    "pydantic>=2.9.2",
    "safety-db",
    "ijson>=3.3.0",
    "rich>=13.9.3",
    "package-schemes>=0.1.0",
]

[project.scripts]
uv-audit = "uv_audit.cli:cli"

[tool.uv]
package = true
dev-dependencies = [
    "mypy>=1.12.1",
    "pre-commit>=4.0.1",
    "pre-commit-hooks>=5.0.0",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.24.0",
    "pytest-cov>=5.0.0",
    "ruff>=0.7.0",
    "types-toml>=0.10.8.20240310",
]

[tool.uv.sources]
safety-db = { git = "https://github.com/pyupio/safety-db/" }

[tool.black]
skip-string-normalization = true
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.ruff]
line-length = 120
target-version = "py312"
unsafe-fixes = true

[tool.ruff.format]
preview = true
quote-style = "single"

[tool.ruff.lint]
preview = true
select = ["A", "B", "C", "D", "E", "F", "I", "UP"]
fixable = ["A", "B", "C", "D", "E", "F", "I", "UP"]
ignore = ["UP004", "D100", "D101", "D102", "D103", "D104", "D107", "D415", "D105", "D106", "D203", "D213", "B008"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.coverage.run]
omit = [
    "*/tests/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
]

[tool.pytest.ini_options]
addopts = "-vvs --tb=short"
xfail_strict = true
testpaths = [
    "tests",
    "integration",
]
python_files = [
    "tests/*.py",
    "test_*.py"
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore:Module already imported:pytest.PytestWarning"
]
log_cli=true
log_level='INFO'
asyncio_mode = "auto"

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
