[project]
name = "process-mining-core"
version = "0.1.1"
authors = [
  { name="Hendrik Reiter", email="hendrik.reiter@email.uni-kiel.de" },
]
description = "A library for selected of process mining datastructures and algorithms"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/HenryWedge/ProcessMiningCore"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
