[project]
name = "nexusai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "toml>=0.10.2",
  "termcolor>=2.5.0",
  "base58>=2.1.1",
  "pyright>=1.1.386",
  "fastapi>=0.115.3",
  "uvicorn>=0.32.0",
  "pydantic-settings>=2.6.0",
  "requests>=2.32.3",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
nexus = "nexus.cli:main"
nexus-service = "nexus.service.main:main"
