[tool.poetry]
name = "oilrad"
version = "0.9.0"
description = "Two stream radiative transfer model for sea ice containing oil droplets."
authors = ["Joseph Fishlock <joseph.fishlock@physics.ox.ax.uk>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.26.4"
scipy = "^1.13.0"


[tool.poetry.group.scripts.dependencies]
matplotlib = "^3.8.4"


[tool.poetry.group.profile.dependencies]
snakeviz = "^2.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
