[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pycobra-ce"
version = "0.0.2"
authors = [
  { name="Invizabel"},
]
description = "pycobra community edition is a basic vulnerabilty scanner!"
readme = "README.md"
license = { file="LICENSE.txt" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = []

[project.urls]
"Homepage" = "https://github.com/Invizabel/pycobra"
"Bug Tracker" = "https://github.com/Invizabel/pycobra"
