[project]
name = "qa-data"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-core>=0.3.12",
    "pydantic>=2.9.2",
]
