[tool.poetry]
name = "kubicle"
version = "0.1.29"
description = "Background jobs on Kubernetes"
authors = ["Patrick Barker <patrickbarkerco@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.8.2"
sqlalchemy = "^2.0.32"
shortuuid = "^1.0.13"
agentcore = "^0.1.0"
kubernetes = "^31.0.0"


[tool.poetry.group.dev.dependencies]
black = "^24.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
